spring: 
  profiles: 
    active:
    - dev
--- 
spring:
  profiles: dev
  application:
    name: microservicecloud-config-icey-dev
--- 
spring:
  profiles: test
  application:
    name: microservicecloud-config-icey-test